### PR TITLE
Investigate numpy.complex64 type

### PR DESCRIPTION
**Pull request by danieljfarrell**
This is incomplete, don't merge!

Just thought I would share with you as it easier to see that reading Gists.

Does it make sense to support complex data types?

### CODE REVIEW

**Comment by cheind** [comment]
Good point, definitely something we currently do not support. A workaround that should already work is to 'cast' complex arrays into a 2-channel floating point array as shown here https://stackoverflow.com/a/47086801/242594

**Comment by cheind** [comment]
does #11 resolve this?

**Comment by danieljfarrell** [comment]
I think it must do. If the tests pass, that's a great solution to serialising arrays. I am right, it casts complex to two float arrays? Makes perfect sense.

**Comment by cheind** [comment]
I believe it does. I will close this for now. In case something comes up, feel free to reopen. And thanks for your contribution!

**Pull request closed without merging**
