### PR TITLE
Add python 3.11 support and test on the CI for all the supported version

### PR DESCRIPTION
**Pull request by AntoineD**

### CODE REVIEW

**Comment by cheind** [comment]
Hey, thanks for PR. There seems to be some issues. I believe the 3.7 and 3.8 issues are not caused by your changes. however for 3.11 some issues arise in poetry. Would you mind checking?

**Comment by AntoineD** [comment]
This is my first time with poetry, all tests pass for all python version on my laptop.

**Comment by AntoineD** [comment]
@cheind Could you please approve running the CI?

**Comment by cheind** [comment]
thanks!

**Pull request merged**
